//
// PaginationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PaginationResponse: Codable {

    /** If the request was successful */
    public var success: Bool?
    /** The next page to query to see more results, whether or not the next page actually exists. */
    public var nextPageNum: Int?
    /** The current page number */
    public var pageNum: Int?


    
    public init(success: Bool?, nextPageNum: Int?, pageNum: Int?) {
        self.success = success
        self.nextPageNum = nextPageNum
        self.pageNum = pageNum
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(success, forKey: "success")
        try container.encodeIfPresent(nextPageNum, forKey: "nextPageNum")
        try container.encodeIfPresent(pageNum, forKey: "pageNum")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        success = try container.decodeIfPresent(Bool.self, forKey: "success")
        nextPageNum = try container.decodeIfPresent(Int.self, forKey: "nextPageNum")
        pageNum = try container.decodeIfPresent(Int.self, forKey: "pageNum")
    }
}

